// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddTask(arg1) {
  return window['go']['tasks']['Tasks']['AddTask'](arg1);
}

export function DeleteTask(arg1) {
  return window['go']['tasks']['Tasks']['DeleteTask'](arg1);
}

export function GetActiveTask() {
  return window['go']['tasks']['Tasks']['GetActiveTask']();
}

export function GetTasks() {
  return window['go']['tasks']['Tasks']['GetTasks']();
}

export function IncrementSession(arg1, arg2) {
  return window['go']['tasks']['Tasks']['IncrementSession'](arg1, arg2);
}

export function SaveTasks() {
  return window['go']['tasks']['Tasks']['SaveTasks']();
}

export function SetActiveTask(arg1) {
  return window['go']['tasks']['Tasks']['SetActiveTask'](arg1);
}

export function ToggleComplete(arg1) {
  return window['go']['tasks']['Tasks']['ToggleComplete'](arg1);
}
