// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GetCurrentCycle():Promise<string>;

export function GetLimitTimeByDescription(arg1:string):Promise<number>;

export function GetNewTime(arg1:number):Promise<string>;

export function GetNextCycle():Promise<string>;

export function GetSessions():Promise<Array<main.Session>>;

export function GetTime(arg1:number):Promise<string>;

export function StartSession(arg1:string):Promise<number>;

export function StopSession():Promise<string>;
