// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetCurrentCycle() {
  return window['go']['main']['Clock']['GetCurrentCycle']();
}

export function GetLimitTimeByDescription(arg1) {
  return window['go']['main']['Clock']['GetLimitTimeByDescription'](arg1);
}

export function GetNewTime(arg1) {
  return window['go']['main']['Clock']['GetNewTime'](arg1);
}

export function GetNextCycle() {
  return window['go']['main']['Clock']['GetNextCycle']();
}

export function GetNextCycleAndAdvance() {
  return window['go']['main']['Clock']['GetNextCycleAndAdvance']();
}

export function GetRemainingMs(arg1) {
  return window['go']['main']['Clock']['GetRemainingMs'](arg1);
}

export function GetSessions() {
  return window['go']['main']['Clock']['GetSessions']();
}

export function GetTime(arg1) {
  return window['go']['main']['Clock']['GetTime'](arg1);
}

export function IsPaused() {
  return window['go']['main']['Clock']['IsPaused']();
}

export function PauseSession(arg1) {
  return window['go']['main']['Clock']['PauseSession'](arg1);
}

export function ResumeSession(arg1) {
  return window['go']['main']['Clock']['ResumeSession'](arg1);
}

export function StartSession(arg1) {
  return window['go']['main']['Clock']['StartSession'](arg1);
}

export function StopSession() {
  return window['go']['main']['Clock']['StopSession']();
}
