// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddTask(arg1) {
  return window['go']['main']['Tasks']['AddTask'](arg1);
}

export function DeleteTask(arg1) {
  return window['go']['main']['Tasks']['DeleteTask'](arg1);
}

export function GetTask(arg1) {
  return window['go']['main']['Tasks']['GetTask'](arg1);
}

export function UpdateTask(arg1, arg2) {
  return window['go']['main']['Tasks']['UpdateTask'](arg1, arg2);
}
