// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AddTask(arg1:string):Promise<main.Task>;

export function DeleteTask(arg1:number):Promise<void>;

export function GetActiveTask():Promise<number>;

export function GetTasks():Promise<Array<main.Task>>;

export function IncrementSession(arg1:number,arg2:string):Promise<void>;

export function SaveTasks():Promise<void>;

export function SetActiveTask(arg1:number):Promise<void>;

export function ToggleComplete(arg1:number):Promise<void>;
