// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AddTask(arg1:main.Task):Promise<void>;

export function DeleteTask(arg1:number):Promise<void>;

export function GetTask(arg1:number):Promise<main.Task>;

export function UpdateTask(arg1:number,arg2:main.Task):Promise<void>;
